INSERT INTO `${TABLE_PREFIX}_user_usergroup_map` VALUES (360,8);
INSERT INTO `${TABLE_PREFIX}_users` VALUES (360,'${ADMIN_USERNAME}','${ADMIN_USERNAME}','${ADMIN_EMAIL}','${ADMIN_PASSWORD_HASH}',0,1,'${INSTALL_DATETIME}','${INSTALL_DATETIME}','0','',NULL,0,'','',0)
